# Generated by Django 2.1 on 2018-11-14 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='Pools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pools_sn', models.CharField(default='', max_length=50, verbose_name='奖池唯一货号')),
                ('name', models.CharField(max_length=100, verbose_name='奖池名')),
                ('bonus_sn', models.CharField(default='', max_length=50, verbose_name='奖号')),
                ('bonus', models.IntegerField(default=0, verbose_name='倍数')),
                ('pools_brief', models.TextField(max_length=500, verbose_name='简短描述')),
                ('pools_front_image', models.ImageField(blank=True, null=True, upload_to='pools/images/', verbose_name='封面图')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间戳')),
            ],
            options={
                'verbose_name': '奖池',
                'verbose_name_plural': '奖池',
            },
        ),
        migrations.CreateModel(
            name='PoolsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('pools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pools.Pools', verbose_name='奖品')),
            ],
            options={
                'verbose_name': '轮播图片',
                'verbose_name_plural': '轮播图片',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='pools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Pools', verbose_name='商品'),
        ),
    ]
