# Generated by Django 2.1 on 2018-11-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_auto_20181114_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pools',
            options={'verbose_name': '奖池规则', 'verbose_name_plural': '奖池规则'},
        ),
    ]
