# Generated by Django 2.1 on 2018-11-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_auto_20181120_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pools',
            options={'verbose_name': '奖池产品规则', 'verbose_name_plural': '奖池产品规则'},
        ),
    ]
