# Generated by Django 2.1 on 2018-11-15 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0002_auto_20181114_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile',
                                              verbose_name='用户')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Pools',
                                           verbose_name='奖池商品')),
                ('betting_sn', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='购买期号')),
                ('nums', models.IntegerField(default=0, verbose_name='数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间戳')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', max_length=30, verbose_name='订单状态')),
                ('post_script', models.CharField(max_length=200, verbose_name='订单留言')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='订单金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间戳')),
                ('betting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Betting', verbose_name='投注单号')),
            ],
            options={
                'verbose_name': '支付生效单',
                'verbose_name_plural': '支付生效单',
            },
        ),
        migrations.CreateModel(
            name='OrderPools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pools_num', models.IntegerField(default=0, verbose_name='奖池商品数量')),
                ('betting_sn', models.CharField(default='', max_length=50, verbose_name='购买期号')),
                ('bonus', models.IntegerField(default=0, verbose_name='中奖金额')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间戳')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pools', to='trade.OrderInfo', verbose_name='订单信息')),
                ('pools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Pools', verbose_name='奖池商品')),
            ],
            options={
                'verbose_name': '奖池订单商品',
                'verbose_name_plural': '奖池订单商品',
            },
        ),
    ]
